### PR TITLE
list of json account_keys instead of separate files

### PR DESCRIPTION
**Pull request by anthony-near**
Suggestion by @anshal-savla to make key management easier (1 credentials file easier to work with and from secretsmanager than multiple)
- [x] consolidate keys from multiple json files to single json file containing a list of json credentials
- [x] test locally

### CODE REVIEW

**Comment by volovyks** [comment]
@anthony-near looks like it should not break prod or dev environments for MPC. But it will break our local test environment. Please, ping me before merging.

**Review by anshal-savla — APPROVED** [review]

**Comment by anshal-savla** [comment]
@anthony-near @volovyks 

I am ready to merge this PR.

I have updated terraform for our relayer deployments and am ready to roll that out once we merge this.

**Comment by volovyks** [comment]
@anshal-savla  fast auth relayer releases should be independent from merges. As I was saying before, we should test this before on our end. It means that we need to have Dcoker image for our tests that is usually deployed with CI.

**Comment by anshal-savla** [comment]
@volovyks how do want to proceed with testing?
Merging this would create a new docker image or we can build a rc image berfore merging.

**Pull request merged**
