### PR TITLE
Docker Registry

### PR DESCRIPTION
**Pull request by volovyks**
#closes https://github.com/near/pagoda-relayer-rs-fastauth/issues/46

### CODE REVIEW

**Comment by volovyks** [comment]
@anshal-savla I do not have access to this repo. We need to add `GCP_CREDENTIALS_DEV` to secrets.

**Comment by itegulov** [comment]
Since this is an open-source repo, I think Docker Hub or [GHCR](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) would suit better here

**Comment by anshal-savla** [comment]
@volovyks I am not able to change to read and write permission for the actions workflow. @nearlysean Can you help with this?

**Comment by nearlysean** [comment]
I have a 🚫 no entry icon when trying to change it, as well. 
image

**Comment by nearlysean** [comment]
It [looks like ](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#how-the-permissions-are-calculated-for-a-workflow-job) it needs to be set at the org level first. I'm a little more nervous to make that change at the NEAR org level.

**Comment by volovyks** [comment]
@nearlysean @anshal-savla we solved this issue, and now it works without extra permissions.

**Comment by nearlysean** [comment]
Great, thanks for working around it. 👍

**Comment by anshal-savla** [comment]
@volovyks curious, what was the workaround?

**Review by anshal-savla — APPROVED** [review]

**Comment by volovyks** [comment]
@anshal-savla GitHub actions could not create a new registry, but it worked once we made it manually. Pushing to it is allowed.
@itegulov thanks for the advice.

**Pull request merged**
